version: '3'

services:
  fastapi:
    volumes:
      - ./fastapi/models:/fastapi/models
    build: fastapi/
    ports: 
      - 8080:8080
    networks:
      - deploy_network
    container_name: fastapi
    

  streamlit:
    volumes:
      - ./streamlit/data:/streamlit/data
    build: streamlit/
    depends_on:
      - fastapi
    ports: 
        - 8501:8501
    networks:
      - deploy_network
    container_name: streamlit



networks:
  deploy_network:
    driver: bridge